#!/usr/bin/env bash
# ============================================================================
#  build.sh — Cloudflare Pages build step
#  Injects environment variables into public/config.js at build time.
#  This keeps the Apps Script Web App URL out of the public repo.
# ============================================================================
set -euo pipefail

API_URL="${API_URL:-}"
SITE_VERSION="${SITE_VERSION:-1.0.0}"
CACHE_TTL_MS="${CACHE_TTL_MS:-21600000}"

cat > public/config.js <<EOF
/* Auto-generated by build.sh — do not edit manually. */
window.PORTFOLIO_CONFIG = {
  API_URL: "${API_URL}",
  CACHE_TTL_MS: ${CACHE_TTL_MS},
  SITE_VERSION: "${SITE_VERSION}",
  SHOW_FALLBACK_BANNER: false
};
EOF

if [ -z "$API_URL" ]; then
  echo "⚠ WARN: API_URL is empty — site will render fallback data."
else
  echo "✓ public/config.js built (version ${SITE_VERSION})"
fi
